### ISSUE TITLE
[Canary 205.5] [Latest] Failed to load Vendetta

### ISSUE THREAD

**Issue by Kitosight** [vendetta-mod/Vendetta#184] opened 2023-11-10 03:52 UTC
As Discord loves, it changed something again in stylesheets (as far as I understood it) so Vendetta started failing to load.

![Screenshot_20231110-064736.png](https://github.com/vendetta-mod/Vendetta/assets/70456337/e9976647-a401-4552-a6d8-d0e4a5c1fbba)

**Comment by nexpid** [comment] 2023-11-10 06:37
aw man I wish they posted an announcement about this

oh wait ![Screenshot_2023-11-10-07-36-33-864_dev.beefers.vendetta-edit.jpg](https://github.com/vendetta-mod/Vendetta/assets/60316309/b02d4470-a484-4b8a-96cf-48f642cf1abd)

![Screenshot_2023-11-10-07-36-47-760_dev.beefers.vendetta-edit.jpg](https://github.com/vendetta-mod/Vendetta/assets/60316309/25267404-f8af-440c-ad13-1d3b72a7f382)

**Comment by TochkaIco** [comment] 2023-11-11 10:15
Yeah, I hope that'll be fixed in a week or smth. I don't really fill out, like using another phone modified discord app😶‍🌫️

**Comment by joeyoropesa-dev** [comment] 2023-11-12 10:03
Can this and #186 be flagged as an bug because it's already confirmed that those bugs we have is for everyone - it's not because we made mistakes with our devices, it's because we have logs and proves that there is basically an bug that needs to be taken seriously

**Comment by janisslsm** [comment] 2023-11-12 10:27
![IMG_20231112_122409.jpg](https://github.com/vendetta-mod/Vendetta/assets/97699850/1e3006a8-7985-45c5-9c80-97ff991160ad)

**Comment by joeyoropesa-dev** [comment] 2023-11-12 10:51
> ![IMG_20231112_122409.jpg](https://github.com/vendetta-mod/Vendetta/assets/97699850/1e3006a8-7985-45c5-9c80-97ff991160ad)
> 
> 

Well is that means thag we will now get two versions of Vendetta Loaders and one of them will be for stable versions only and another one for beta/alpha?

**Comment by stikhead** [comment] 2023-11-12 11:00
*Probably No*, we have to wait until Discord stable gets 204.x

**Comment by joeyoropesa-dev** [comment] 2023-11-12 11:02
> *Probably No*, we have to wait until Discord stable gets 204.x 

Well in that case I will probably join beta program before it begins to be full - yeah, it's buggy on my MIUI firmware but if Vendetta is going to apply fix for 204+ versions (beta/alpha builds) and left older versions bricked, I need to migrate to beta/alpha versions.

**Comment by h-exx** [comment] 2023-11-15 18:43
Beta 205.8 seems to fix this issue for me

**Comment by nexpid** [comment] 2023-11-15 18:44
yeah because this was fixed

**Comment by h-exx** [comment] 2023-11-15 18:45
just letting people know here in case they dont look at the discord

**Comment by Poopooracoocoo** [comment] 2023-11-15 18:55
>Beta 205.8 seems to fix this issue for me

I didn't know Vendetta could update by itself. I was pleasantly surprised to see that 204201 (alpha) started working without me needing to update it using Vendetta Manager. I then got to do a cloud backup and went back to stable, where I no longer see the glitched theme. Thanks Amsyar, Kasi and Maisy <3

**Comment by joeyoropesa-dev** [comment] 2023-11-15 19:26
This issue should be closed because the fix is published Globally to official server from where Vendetta code is loaded by default in every Vendetta apk

**Closed as completed** 2023-12-04 11:07 UTC
