### ISSUE TITLE
Weird behaviour with Android 13 themed icons

### ISSUE THREAD

**Issue by madkarmaa** [vendetta-mod/Vendetta#167] opened 2023-10-19 05:23 UTC
![Screenshot_2023-10-19-07-19-48-41_b783bf344239542886fee7b48fa4b892.jpg](https://github.com/vendetta-mod/Vendetta/assets/100418457/7ce231f8-3406-40d6-a696-1013553a8cb8)

This is how the patched Discord app looks using the custom Vendetta icon.

App version: 193.13 stable

**Comment by Cynosphere** [comment] 2024-01-24 20:03
Duplicate of #214 and #119

**Closed as not planned by Cynosphere** 2024-01-24 20:03 UTC
Labels: duplicate, wontfix
